spring:
  application:
    name: opentelemetry

  datasource:
    url: jdbc:postgresql://localhost:5432/mydb
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect